#!/usr/bin/env python3
"""Regenerate benchmarks/rtllm_manifest.yaml from RTLLM tree."""
from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RTLLM = Path(os.environ.get("RTLLM_ROOT", ROOT.parent / "RTLLM"))
OUT = ROOT / "benchmarks" / "rtllm_manifest.yaml"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rtllm_top_module import makefile_module, resolve_top_module  # noqa: E402


def main() -> None:
    if not RTLLM.is_dir():
        raise SystemExit(f"RTLLM not found: {RTLLM}")

    problems = []
    for desc in sorted(RTLLM.rglob("design_description.txt")):
        pdir = desc.parent
        rel = pdir.relative_to(RTLLM).as_posix()
        pid = pdir.name
        top = resolve_top_module(pdir)
        make = makefile_module(pdir)
        if make != top:
            print(f"note: {pid}: makefile TEST_DESIGN={make!r} -> top_module={top!r}", file=sys.stderr)
        problems.append({"id": pid, "path": rel, "top_module": top})

    lines = [
        "# RTLLM v2.0 — auto-generated by scripts/gen_manifest.py",
        f"# RTLLM_ROOT: {RTLLM}",
        "# top_module: testbench DUT name, else SPEC Module name, else makefile TEST_DESIGN",
        "version: 1",
        f"count: {len(problems)}",
        "problems:",
    ]
    for i, p in enumerate(problems, start=1):
        lines.append(f"  - index: {i}")
        lines.append(f"    id: {p['id']}")
        lines.append(f"    path: {p['path']}")
        lines.append(f"    top_module: {p['top_module']}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(problems)} problems to {OUT}")


if __name__ == "__main__":
    main()
